### ISSUE TITLE
[BUG]: Cannot install on VSCode 1.75.1

### ISSUE THREAD

**Issue by chris3ware** [adamiBs/vscode-terraform-live-graph#9]
**Describe the bug**
Unable to install the extension

**To Reproduce**
1. Go to VSCode Extensions marketplace
2. Click on 'install'
3. See error

**Expected behavior**
The extension should install

**Screenshots**
<img width="615" alt="Screenshot 2023-03-16 at 12 31 39" src="https://user-images.githubusercontent.com/36608309/225617952-032a515e-3968-4fd7-8297-43e935a666b2.png">

**Versions (please complete the following information):**
 - OS: macOS Big Sur 11.7.4
 - VSCode Version: 1.75.1
 - Terraform Live Graph Extension for VSCode Version 0.0.4
 - Terraform Version: N/A

**Additional context**

**Comment by adamiBs** [comment]
Hi thanks for the issue, I'll look into this, currently the extension has been tested on `v1.76.X`, I think that the extension should work on older versions but this requires a bit of testing in order to validate the assumption.
Once validated, I'll release a version that is compatible with older versions.

**Comment by adamiBs** [comment]
I've looked into this and I can conclude that `^v1.75.0` seems compatible as well.

**Comment by adamiBs** [comment]
This will ship today in an updated version of the extension `v0.0.5`.

**Comment by adamiBs** [comment]
I've published `v0.0.5`. Closing issue.
